### ISSUE TITLE
Location of the canis folder required to apply v1.16 patch

### ISSUE THREAD

**Issue by BrosDs** [kentindell/canhack#13]
Hi, 

I was following the README.txt found in canhack/pico/micropython/ to apply the patch on the firmware of the CANPico board but I cannot find the canis folder nor its content in any directory of this repo. Could you please provide some more info about this procedure?

Thanks

**Comment by kentindell** [comment]
The v1.16 patch is applied over the top of the patched v1.15. To get that you need to apply the v1.15 patch, which is in the folder ``OLD``.

**Comment by BrosDs** [comment]
I've tried running the git apply command with the v1.15 patch but it failed (multiple errors on many source files). Is there a particular undocumented way to apply the patch?

**Comment by kentindell** [comment]
The v1.15 patch is against MicroPython 1.15. But I'll see if I can just lift the ``canis`` folder out and drop it directly into the repo here, which would save the hassle. The firmware is due to be brought up to date with MicroPython anyway, and I'll find a better way to do the next release.

**Comment by kentindell** [comment]
The v1.18 bump, with the ``canis`` source code broken out, is staged on:

[micropython_v1_18](https://github.com/kentindell/canhack/tree/micropython_v1_18)

Give the new instructions a try and let me know if it doesn't build.

**Comment by kentindell** [comment]
It's now been merged into the master branch.
