### ISSUE TITLE
Docs mistake: CANHack_schm.pdf same as CANProbe_schm.pdf

### ISSUE THREAD

**Issue by nico0481** [kentindell/canhack#3]
Hello,

Nice job!

I think there is a mistake in : https://github.com/kentindell/canhack/tree/master/docs/pdf

CANHack_schm.pdf seems to be the same as CANProbe_schm.pdf, no RaspberryPico on CANHack_schm.pdf, and the name of the schematic sheet is CANProbe with DB9.

Best regards

Nico

**Comment by kentindell** [comment]
This is correct - it was a file upload snafu ("you are trapped in a maze of twisty file systems, all alike"). It's fixed in my branch, which also has new API docs and new firmware. It'll be pushed as soon as I finalize the patch against the MicroPython repo.

**Comment by jdutchak** [comment]
are you able to include the schematics kicad project files and not just the pdf

**Comment by kentindell** [comment]
Doesn't CANHack.kicad_pcb work?

**Comment by jdutchak** [comment]
Yes but when I attempt to look at the sch i get this message 
Schematic “/Users/j/Projects/canhack/pico/CANHack.sch” does not exist.  Do you wish to create it?

**Comment by jdutchak** [comment]
also is your pico board for sale ? or do I need to buy this one here https://www.cnx-software.com/2021/05/26/canpico-open-source-board-adds-can-bus-to-raspberry-pi-pico/

**Comment by kentindell** [comment]
You can buy the CANPico from our distributor SK Pang: https://www.skpang.co.uk/collections/can-bus-boards/products/canpico-board (it comes with a Pico soldered down)

**Comment by jdutchak** [comment]
Thank you just purchased, are the .sch files available? is the IDPS in the firmware of this project?

**Comment by kentindell** [comment]
There's no IDPS in the CANPico firmware: the firmware contains a Python CAN API and a low-level protocol hacking API. The IDPS we are developing uses custom hardware to see low-level CAN bus events and to decode out-of-band data put into CAN frames to tag the physical source of the frame.

**Comment by jdutchak** [comment]
I see, is that something I can purchase then? the IDPS ?

**Comment by kentindell** [comment]
A CANPico with custom hardware on it is under consideration :-)
